export const enumLabels: Record<string, Record<string, string>> = {
  "AlcoholTypeEnum": {
    "Beer": "Beer",
    "Wine": "Wine",
    "HardLiquor": "Hard Liquor",
  },
  "CrampsSeverityEnum": {
    "Mild": "Mild",
    "Moderate": "Moderate",
    "Heavy": "Heavy",
  },
  "DrugTypeEnum": {
    "Marijuana": "Marijuana",
    "Cocaine": "Cocaine",
    "Meth": "Meth",
    "Opioids": "Opioids",
    "Heroin": "Heroin",
    "LSD": "LSD",
    "PCP": "PCP",
    "EcstasyMolly": "Ecstasy Molly",
    "PrescriptionDrugs": "Prescription Drugs",
    "OverTheCounter": "Over The Counter",
  },
  "EmploymentTypeEnum": {
    "EmployedFullTime": "Employed Full Time",
    "EmployedPartTime": "Employed Part Time",
    "SelfEmployed": "Self Employed",
    "UnemployedLooking": "Unemployed Looking",
    "UnemployedNotLooking": "Unemployed Not Looking",
    "Student": "Student",
    "Homemaker": "Homemaker",
  },
  "FamilyRelationEnum": {
    "Myself": "Myself",
    "GrandParents": "Grand Parents",
    "Parents": "Parents",
    "Siblings": "Siblings",
    "Kids": "Kids",
    "ExtendedFamily": "Extended Family",
  },
  "FrequencyEnum": {
    "Daily": "Daily",
    "Weekly": "Weekly",
    "Weekends": "Weekends",
    "Monthly": "Monthly",
  },
  "IncomeEnum": {
    "NoIncome": "No Income",
    "WelfareSSIBenefits": "Welfare SSIBenefits",
    "Group1": "Group1",
    "Group2": "Group2",
    "Group3": "Group3",
    "Group4": "Group4",
    "Group5": "Group5",
    "Group6": "Group6",
    "Group7": "Group7",
  },
  "InsuranceCompanyEnum": {
    "MedicaidFullCoverage": "Medicaid Full Coverage",
    "EmergencyMedicaid": "Emergency Medicaid",
    "AnthemBlueCrossBlueShield": "Anthem Blue Cross Blue Shield",
    "Aetna": "Aetna",
    "Cigna": "Cigna",
    "CompassRoseHealthPlan": "Compass Rose Health Plan",
    "HometownHealthPlan": "Hometown Health Plan",
    "ProminenceHealthPlan": "Prominence Health Plan",
    "SierraHealthAndLife": "Sierra Health And Life",
    "HealthPlanOfNevada": "Health Plan Of Nevada",
    "UnitedHealthCareGroup": "United Health Care Group",
    "Humana": "Humana",
    "Culinary": "Culinary",
    "AmerigroupNevada": "Amerigroup Nevada",
    "IDontKnow": "IDont Know",
    "Other": "Other",
  },
  "LivingEnum": {
    "Alone": "Alone",
    "Parent": "Parent",
    "BoyfriendFiance": "Boyfriend Fiance",
    "Friends": "Friends",
    "Spouse": "Spouse",
  },
  "MedicaidStatusEnum": {
    "Approved": "Approved",
    "Denied": "Denied",
    "Pending": "Pending",
  },
  "STDTestResultEnum": {
    "Negative": "Negative",
    "Positive": "Positive",
  },
  "STDTypesEnum": {
    "Gonorrhea": "Gonorrhea",
    "Chlamydia": "Chlamydia",
    "Herpes": "Herpes",
    "HepatitisB": "Hepatitis B",
    "HIV": "HIV",
    "Syphilis": "Syphilis",
    "GenitalWarts": "Genital Warts",
    "PelvicInflammatoryDisease": "Pelvic Inflammatory Disease",
    "Trichomonas": "Trichomonas",
    "Hpv": "Hpv",
  },
  "ScreeningHealthHistoryEnum": {
    "SevereAsthma": "Severe Asthma",
    "HeartBloodDisease": "Heart Blood Disease",
    "KidneyChronicDisease": "Kidney Chronic Disease",
    "BariatricSurgery": "Bariatric Surgery",
    "Seizures": "Seizures",
    "HBP": "HBP",
    "Diabetes": "Diabetes",
    "Autoimmune": "Autoimmune",
    "Thyroid": "Thyroid",
  },
  "TobaccoTypeEnum": {
    "Cigarettes": "Cigarettes",
    "Vaping": "Vaping",
    "Chew": "Chew",
  },
};
export default enumLabels;